l_english:
 SETTING_INPUT_CONTEXT_COMMON: "Загальне"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Прив'язки клавіш для загальних значень введення"

 SETTING_INPUT_ACTION_PAUSE: "Призупинити/продовжити"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Збільшити швидкість"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Зменшити швидкість"
 SETTING_INPUT_ACTION_SPEED_ONE: "Швидкість 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Швидкість 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Швидкість 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Швидкість 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Швидкість 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Пісня: павза/відтворити"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Наступна пісня"
 SETTING_INPUT_ACTION_CAMERA_UP: "Рух знімача вверх"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Рух знімача ліворуч"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Рух знімача вниз"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Рух знімача праворуч"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Шукання місцин"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Політика"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Бюджет"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Будівлі"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Ринок"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Збройні сили"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Дипломатія"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Технології"
 SETTING_INPUT_ACTION_OPEN_CULTURE: "Культури"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Населення"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Часопис"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Силовий блок"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Підприємства"
 SETTING_INPUT_ACTION_MAP_LIST: "Облік"
 SETTING_INPUT_ACTION_BACK: "Назад"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Плянувальник"
 SETTING_INPUT_ACTION_TAB_1: "Вкладка 1"
 SETTING_INPUT_ACTION_TAB_2: "Вкладка 2"
 SETTING_INPUT_ACTION_TAB_3: "Вкладка 3"
 SETTING_INPUT_ACTION_TAB_4: "Вкладка 4"
 SETTING_INPUT_ACTION_TAB_5: "Вкладка 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Сочка виробництва"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Сочка політики"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Сочка дипломатії"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Сочка збройних сил"
 SETTING_INPUT_ACTION_TRADE_LENS: "Сочка торгівлі"
 SETTING_INPUT_ACTION_CONFIRM: "Підтвердити"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Нинішня ситуація"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Черга на будівництво"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Черга: павза/продовжити"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Детальніше"
 SETTING_INPUT_ACTION_SCROLL_UP: "Прокрутити вгору"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Прокрутити вниз"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED:0 "Show Pinned in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY:0 "Show Economy in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS:0 "Show Politics in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY:0 "Show Diplomacy in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY:0 "Show Military in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL:0 "Show All in Outliner" 
 SETTING_INPUT_ACTION_TOGGLE_PIN:0 "Toggle Pin"
 SETTING_INPUT_ACTION_ZOOM_TO: "Наблизити до"